### ISSUE TITLE
RGB colored player names have color annotations in them 

### ISSUE THREAD

**Issue by Parsonswy** [peacefulcraft-network/CowBot#9]
Player names in #gamechat have &x in them where player's have inserted RGB color codes.

**Comment by Parsonswy** [comment]
![image](https://user-images.githubusercontent.com/13711521/141882315-876b3710-85a2-41bd-82e0-1219c60da2ba.png)

**Comment by michaeljecmen** [comment]
Hey @Parsonswy. Did some digging into this issue and believe I've got to the crux of the problem here -- the [legacy way of formatting RGB minecraft nicknames](https://minecraft.fandom.com/wiki/Formatting_codes) uses the § prefix character, while the new, MultiChat ([since MultiChat 1.9.6, it seems](https://www.spigotmc.org/resources/multichat-full-rgb-colour-support.26204/update?update=348529)) way uses & for prefixing color codes, and &x to prefix any full 6 digit hex colors. 

That said, the most recent version of the BungeeCord API (which PCN is using, the 1.17 snapshot) only checks for the old formatting when stripping colors in its net.md_5.bungee.api.ChatColor::stripColor method. (note that \u00A7 is unicode for §, and the & is never matched against)

![image](https://user-images.githubusercontent.com/43277421/144694281-451819a0-4ce9-413d-8b94-0a6e8c99234d.png)
![image](https://user-images.githubusercontent.com/43277421/144694305-e4ede002-56ec-4b1d-9fc0-beb2292bb2ac.png)

I've done quite a bit of googling and can't seem to find a clean solution here, but because only the "&x" formatting characters slip through, and & isn't a valid username character, I'm proposing we manually re-strip the stripped message for all instances of "&x". If this sounds good I'll throw up a PR.

**Comment by michaeljecmen** [comment]
(Furthermore, I should mention I've tested the fix and it works without any side effects that I've noticed)

**Comment by Parsonswy** [comment]
Sounds good to me 👍.
